### ISSUE TITLE
Question: Contributions to this project should be made in any specific Flutter Version?

### ISSUE THREAD

**Issue by evandrmb** [Flutterando/flutter_web_site#15]
I'm currently using _Flutter 1.24.0-10.2.pre_

Can't recall in wich version Flutter introduces a widget called Router which conflicts with Router from Modular. In recent versions Modular uses ModularRouter instead of Router.

Should we develop in a specific Flutter version or just update Modular?

**Comment by jacobaraujo7** [comment]
Hello!
Thanks for contrubutions
